version = 1

test_patterns = [
  'tests/test_*.py'
]

exclude_patterns = [
  
]

[[analyzers]]
name = 'python'
enabled = true
runtime_version = '3.x.x'

[[analyzers]]
name = "test-coverage"
enabled = true