language: python
python:
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt

addons:
  sonarcloud:
    organization: "clslgrnc-github"

# command to run tests
script:
  - python -m unittest tests/test_*.py
  - sonar-scanner

cache: pip  