language: python
python:
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coverage

addons:
  sonarcloud:
    organization: "clslgrnc-github"

# command to run tests
script:
  - coverage run --source tbrop -m unittest tests/test_*.py
  - coverage xml
  - sonar-scanner

cache: pip  